### ISSUE TITLE
Correct Typos in Website Text

### ISSUE THREAD

**Issue by nown1ne** [nown1ne/mail#10]
Description: Improve the website by fixing any typos or spelling errors in the text content. Review pages and make corrections.

Difficulty: Very Easy
Tags: Proofreading, Text

**Comment by musadiqpeerzada** [comment]
@nown1ne Assign me

**Comment by avelynhc** [comment]
@nown1ne Hi! I would like to work on this issue. Can you kindly assign this issue to me please? Thanks!

**Comment by nown1ne** [comment]
Yes you can go ahead 
Make sure to find as many as you can 🚀

**Comment by Preetraj2002** [comment]
Hey i see this issue still open can you please assign me the task i will do it in 1 day @nown1ne

**Comment by avelynhc** [comment]
@nown1ne I just pushed the pr for this issue.
