### ISSUE TITLE
Improve the Hamburger Menu

### ISSUE THREAD

**Issue by nown1ne** [nown1ne/mail#11]
The current hamburger menu on our website doesn't blend seamlessly with our design language, creating a visual inconsistency. This issue aims to enhance the hamburger menu's design to ensure it aligns harmoniously with the overall website design.

Difficulty - Hard
Tags - Enhancement, UI/UX, Design

**Comment by suresh8919** [comment]
Hey @nown1ne Please assign me this

**Comment by suresh8919** [comment]
Hello @nown1ne What improvements you are expecting in hamburger

**Comment by suresh8919** [comment]
hey @nown1ne , @IshaanAdarsh bro  can you give a brief info about HackSquad 2023 happening from oct -1 to oct-31 , how to contribute , contributions in hacktoberfest will  also be  counted for hacksquad too , or is there any other specific repository to contribute please guide me 
thank you

**Comment by IshaanAdarsh** [comment]
@suresh8919 I think hacksquad is different from Hacktoberfest. They have different guidelines and Repos to contribute to. You can get a better idea by reading this:
https://medium.com/@chauhanomprakash7206/hacksquad-20223-contribute-meet-participate-and-win-swag-9485c6714b38
