### ISSUE TITLE
Center the Input and Button 

### ISSUE THREAD

**Issue by nown1ne** [nown1ne/mail#13]
**Describe the bug**
Center the input field and button in the email viewing page of others section

**To Reproduce**
1. Go to 'ezmail.vercel.app/others'
2. Click on any of the templates
3. Notice the input and buttons

**Difficulty** 
Medium

**Expected behavior**
Center the input and bbutton while keeping the page responsive

**Screenshots**
![image](https://github.com/nown1ne/ezmail/assets/25835195/0011de47-1ca6-4898-ba27-4700314317e3)

**Comment by suresh8919** [comment]
hey @nown1ne Please assign me this

**Comment by praveen-p09** [comment]
Hi! I'd like to work on this issue. Please assign it to me.

**Comment by Preetraj2002** [comment]
I can work on this. Please give me a chance to make my initial contributions in open source. @nown1ne assign me the task

**Comment by Sha1kh4** [comment]
Please check my PR

**Comment by suresh8919** [comment]
Hello @nown1ne can you please assign me this
