### ISSUE TITLE
Improve the footer

### ISSUE THREAD

**Issue by nown1ne** [nown1ne/mail#14]
**Describe the bug**
Improve the footer section of the page

**To Reproduce**
1. Go to 'ezmail.vercel.app'
2. Scroll Down to the footer
3. Notice the links section of the footer

**Difficulty** 
Medium

**Expected behavior**
Move the links section to the right side of the page while keeping the page reponsive

**Screenshots**
![image](https://github.com/nown1ne/ezmail/assets/25835195/314f27a5-3be3-4ce3-8ccd-44cdf0fb6ff3)

**Comment by suresh8919** [comment]
Hey @nown1ne Please assign me this

**Comment by yashwanthvarma18** [comment]
Hello @nown1ne , I'm eager to contribute. Please assign me
