### ISSUE TITLE
Make the features section responsive

### ISSUE THREAD

**Issue by nown1ne** [nown1ne/mail#15]
**Describe the bug**
Make the features grid responsive

**To Reproduce**
1. Go to 'ezmail.vercel.app'
2. Scroll down to the features section
3. Open inspect tools and observe for different screen sizes

**Difficulty** 
Medium

**Expected behavior**
The features grid should adjust as per the screen size to allow for easy reading and comfortable reading.

**Screenshots**
![image](https://github.com/nown1ne/ezmail/assets/25835195/abd6ac3a-8cfd-4da5-b225-7f4766837521)
![image](https://github.com/nown1ne/ezmail/assets/25835195/fdec68f0-1702-4756-8465-0b8d3b29c4f6)

**Comment by yashwanthvarma18** [comment]
Hello @nown1ne , I'm eager to contribute. Please assign me

**Comment by suresh8919** [comment]
Hey @nown1ne Please assign me this

**Comment by nown1ne** [comment]
Hello Collaborators,

We want to foster a collaborative and inclusive environment on our GitHub repository. To ensure everyone gets a chance to participate, we'll be assigning only one issue to each person initially. Once you've completed your assigned task, feel free to pick up another issue or create your own. Let's make sure everyone has the opportunity to contribute and learn together! 🌟🤝
