### ISSUE TITLE
Make the prof section responsive

### ISSUE THREAD

**Issue by nown1ne** [nown1ne/mail#16]
**Describe the bug**
The prof section of the website is not responsive for smaller screens 

**To Reproduce**
1. Go to 'ezmail.vercel.app/prof'
2. Open inspect tools and observe for different screen sizes

**Difficulty** 
Medium

**Expected behavior**
Make the template grid responsive for all screens to imrpove readability of the website

**Screenshots**
![image](https://github.com/nown1ne/ezmail/assets/25835195/78603e8e-bba3-45f8-9b0b-378386f78878)
![image](https://github.com/nown1ne/ezmail/assets/25835195/851bad90-8df2-432b-b4d5-6fceb507f9d5)

**Comment by suresh8919** [comment]
Hey @nown1ne Please assign me this

**Comment by Kraniket901** [comment]
I want to work on it !
