### ISSUE TITLE
Make the Our Team section responsive

### ISSUE THREAD

**Issue by nown1ne** [nown1ne/mail#17]
## Describe the bug
The our team section of the homepage is not responsive for smaller screens

To Reproduce

1. Go to 'ezmail.vercel.app/'
2. Scroll Down to the our team section
3. Open inspect tools and observe for different screen sizes

**Difficulty**
Medium

## Expected behavior
Make the section responsive to all screens

## Screenshots
![image](https://github.com/nown1ne/ezmail/assets/25835195/93560077-00b6-496c-b83f-57eab0c01a21)
![image](https://github.com/nown1ne/ezmail/assets/25835195/5ed144dc-89e6-40b8-9ccb-75c946f32f98)

**Comment by yashwanthvarma18** [comment]
Hello @nown1ne , I'm eager to contribute. Please assign me this  task

**Comment by yashwanthvarma18** [comment]
hhey @IshaanAdarsh please checkout my pull request

**Comment by yashwanthvarma18** [comment]
hey @nown1ne  please checkout my pull request

**Comment by yashwanthvarma18** [comment]
Hi @IshaanAdarsh, have you participated in or successfully completed the Google Summer of Code (GSoC) program in the past year? If you have, I would like to get in touch with you to gather valuable information. I'm interested in learning about your experiences, how to get started, preparation strategies, areas to focus on, and what qualities companies look for in GSoC applicants.

**Comment by IshaanAdarsh** [comment]
> Hi @IshaanAdarsh, have you participated in or successfully completed the Google Summer of Code (GSoC) program in the past year? If you have, I would like to get in touch with you to gather valuable information. I'm interested in learning about your experiences, how to get started, preparation strategies, areas to focus on, and what qualities companies look for in GSoC applicants.

You can DM me on my LinkedIn profile. 
We can talk there

**Comment by yashwanthvarma18** [comment]
hey bro  i am unable to DM you because i dont have a premium plan 
any other alternative 
you can trust me I am a student from IIT Madrass sophomore @IshaanAdarsh

**Comment by IshaanAdarsh** [comment]
> hey bro  i am unable to DM you because i dont have a premium plan 
> any other alternative 
> you can trust me I am a student from IIT Madrass sophomore @IshaanAdarsh 
> 

I just accepted your request. Let's talk there.
