### ISSUE TITLE
Improve Alt Text for Images

### ISSUE THREAD

**Issue by nown1ne** [nown1ne/mail#4]
Description: Accessibility is a top priority for us, and we want to ensure that every image on our website is accompanied by descriptive and meaningful alt text. We need contributors who are committed to reviewing and updating alt text where necessary. By doing so, we can make our content accessible to a wider audience, including those who rely on screen readers.

- Difficulty: Easy

- Tags: Accessibility, Images

**Comment by yashwanthvarma18** [comment]
Hello @nown1ne , I'm eager to contribute. Please assign me

**Comment by suresh8919** [comment]
Hey @nown1ne Please assign me this I'm ready to contribute
