### ISSUE TITLE
Fix Image URL

### ISSUE THREAD

**Issue by nown1ne** [nown1ne/mail#6]
Description: The image in the top left corner of the site is currently linked with an absolute URL. To prevent caching and ensure it remains accessible, consider using a relative URL that points to the ezmail.png file in the static directory.

Difficulty: Low
Tags: Bug, Website, Image, URL

**Comment by suresh8919** [comment]
Hey @nown1ne please assign me this

**Comment by praveen-p09** [comment]
Hi! I'd like to work on this issue. Can you please assign it to me?

**Comment by praveen-p09** [comment]
@nown1ne Review requested. Please suggest if any changes need to be done.
