### ISSUE TITLE
Identify and Fix Broken Links

### ISSUE THREAD

**Issue by nown1ne** [nown1ne/mail#7]
Description: Ensure a seamless user experience by identifying and fixing any broken links on the website.Review the site's links and update or remove any links that no longer work.

Difficulty: Easy
Tags: Links, User Experience

**Comment by praveen-p09** [comment]
Hi! I'd like to work on this issue. Can you please assign it to me?

**Comment by praveen-p09** [comment]
PR #20 
Please review and mark it under Hacktoberfest.

**Comment by praveen-p09** [comment]
I tried to use static png in logo but it required some changes in project structure (Assets in public cannot be imported from JavaScript. Instead of /static/ezmail.png, put the file in the src directory, and use /src/ezmail.png instead.)
Shall I do it?

**Comment by praveen-p09** [comment]
I'm a beginner. So if you could suggest any other way to fix that, I'd be happy to do it.

**Comment by nown1ne** [comment]
Yes you can proceed with that
Please make sure that you mention/tag me if asking questions
Cheers
